version: '2'
services:
  db:
    image: 'orozcohsu/docker-alpine-mysql'
    volumes:
       - '/mysql/data/:/var/lib/mysql'
    restart: 'always'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
       MYSQL_ROOT_PWD: '123'
       MYSQL_DATABASE: 'iii'
       MYSQL_USER: 'orozco'
       MYSQL_USER_PWD: '123'
